<?php
$content = <<<HTML
  <div class="all_users_wrapper" >
    <section class="all_users" id="allUsers">
      <div class="all_users_header">
        <p>Name</p>
        <p>Email address</p>
        <p>Role</p>
      </div>
      <ul class="user-list">
        <li>
          <p>Adam</p>
          <p>adam@test.com</p>
          <p>Admin</p>
          <div>
            <button>Edit</button>
            <button>Delete</button>
          </div>
        </li>
          <li>
          <p>Adam</p>
          <p>adam@test.com</p>
          <p>Admin</p>
          <div>
            <button>Edit</button>
            <button>Delete</button>
          </div>
        </li>
           <li>
          <p>Adam</p>
          <p>adam@test.com</p>
          <p>Admin</p>
          <div>
            <button>Edit</button>
            <button>Delete</button>
          </div>
        </li>
           <li>
          <p>Adam</p>
          <p>adam@test.com</p>
          <p>Admin</p>
          <div>
            <button>Edit</button>
            <button>Delete</button>
          </div>
        </li>
           <li>
          <p>Adam</p>
          <p>adam@test.com</p>
          <p>Admin</p>
          <div>
            <button>Edit</button>
            <button>Delete</button>
          </div>
        </li>
           <li>
          <p>Adam</p>
          <p>adam@test.com</p>
          <p>Admin</p>
          <div>
            <button>Edit</button>
            <button>Delete</button>
          </div>
        </li>
           <li>
          <p>Adam</p>
          <p>adam@test.com</p>
          <p>Admin</p>
          <div>
            <button>Edit</button>
            <button>Delete</button>
          </div>
        </li>
           <li>
          <p>Adam</p>
          <p>adam@test.com</p>
          <p>Admin</p>
          <div>
            <button>Edit</button>
            <button>Delete</button>
          </div>
        </li>
           <li>
          <p>Adam</p>
          <p>adam@test.com</p>
          <p>Admin</p>
          <div>
            <button>Edit</button>
            <button>Delete</button>
          </div>
        </li>
           <li>
          <p>Adam</p>
          <p>adam@test.com</p>
          <p>Admin</p>
          <div>
            <button>Edit</button>
            <button>Delete</button>
          </div>
        </li>
           <li>
          <p>Adam</p>
          <p>adam@test.com</p>
          <p>Admin</p>
          <div>
            <button>Edit</button>
            <button>Delete</button>
          </div>
        </li>
           <li>
          <p>Adam</p>
          <p>adam@test.com</p>
          <p>Admin</p>
          <div>
            <button>Edit</button>
            <button>Delete</button>
          </div>
        </li>
           <li>
          <p>Adam</p>
          <p>adam@test.com</p>
          <p>Admin</p>
          <div>
            <button>Edit</button>
            <button>Delete</button>
          </div>
        </li>
           <li>
          <p>Adam</p>
          <p>adam@test.com</p>
          <p>Admin</p>
          <div>
            <button>Edit</button>
            <button>Delete</button>
          </div>
        </li>
           <li>
          <p>Adam</p>
          <p>adam@test.com</p>
          <p>Admin</p>
          <div>
            <button>Edit</button>
            <button>Delete</button>
          </div>
        </li>
           <li>
          <p>Adam</p>
          <p>adam@test.com</p>
          <p>Admin</p>
          <div>
            <button>Edit</button>
            <button>Delete</button>
          </div>
        </li>
           <li>
          <p>Adam</p>
          <p>adam@test.com</p>
          <p>Admin</p>
          <div>
            <button>Edit</button>
            <button>Delete</button>
          </div>
        </li>
            <li>
          <p>Adam</p>
          <p>adam@test.com</p>
          <p>Admin</p>
          <div>
            <button>Edit</button>
            <button>Delete</button>
          </div>
        </li>
      </ul>
    </section>
    <button class="add-user-button" onclick="window.location.href='add_user.php'">Add User</button>
  </div>
  HTML;

require "../../includes/layout.php"

  ?>